# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d4e15a949ecad1a2ced0d1aecdb468fb4908efa35e1def38b9e7b8d55f666b0e19782e4a27ec214f255fe043ebd52dfd86495483d4d17e5da3af82483d2bde5

test:
  secret_key_base: f66d8828274cbd136ed81cbb71a263fa8a91c00ab1afa35c3a892280e0db3fe5a687a783a68d4d2fb7d0db5db97af32de360c904fac67e9793dab9601d208d9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
